In [2]:
import numpy as np

In [3]:
arr1 = np.array([15, 23, 63, 94, 75])

np.mean(arr1)

54.0

In [4]:
np.std(arr1)

30.34468652004828

In [5]:
np.var(arr1)

920.8

In [6]:
np.sum(arr1)

270

In [7]:
np.prod(arr1)

153231750

In [10]:
arr2 = range(1, 6)

print(np.add(arr2, arr1))

[16 25 66 98 80]


In [27]:
matrix1 = np.array([[1, 2, 3], [4, 5, 6]])
matrix2 = np.array([[7, 8, 9], [10, 11, 12], [13, 14, 15]])

matrix1, matrix2

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[ 7,  8,  9],
        [10, 11, 12],
        [13, 14, 15]]))

In [28]:
print(np.dot(matrix1, matrix2))

[[ 66  72  78]
 [156 171 186]]


In [29]:
print(matrix1 @ matrix2)

[[ 66  72  78]
 [156 171 186]]


In [34]:
print(np.tensordot(matrix1, matrix2, axes=(1, 0)))
print('\n')
print(np.tensordot(matrix1, matrix2, axes=(1, 1)))

[[ 66  72  78]
 [156 171 186]]


[[ 50  68  86]
 [122 167 212]]


In [36]:
matrix3 = np.diag(np.arange(3))

matrix3

array([[0, 0, 0],
       [0, 1, 0],
       [0, 0, 2]])

In [41]:
arr3 = np.arange(1, 11)

arr3[2:9:3]

array([3, 6, 9])

In [42]:
print(arr3 + 1.5)

[ 2.5  3.5  4.5  5.5  6.5  7.5  8.5  9.5 10.5 11.5]


In [46]:
print(np.around((arr3 + 1.4)))
print(np.around((arr3 + 1.5)))
print(np.around((arr3 + 1.6)))

[ 2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]
[ 2.  4.  4.  6.  6.  8.  8. 10. 10. 12.]
[ 3.  4.  5.  6.  7.  8.  9. 10. 11. 12.]


In [49]:
arr4 = matrix1.flatten()

arr4

array([1, 2, 3, 4, 5, 6])

In [54]:
repeat_arr = np.arange(1, 4)

print(np.repeat(repeat_arr, 3))
print(np.tile(repeat_arr, 3))
print(np.copy(repeat_arr))

[1 1 1 2 2 2 3 3 3]
[1 2 3 1 2 3 1 2 3]
[1 2 3]
