In [5]:
import numpy as np

np.__version__

'1.21.5'

In [27]:
array1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

array1.shape

(9,)

In [28]:
array1[1:4]

array([2, 3, 4])

In [11]:
indexes = [3, 4, 5]

array1[indexes]

array([4, 5, 6])

In [13]:
mask = (array1 % 2 == 0)

mask

array([False,  True, False,  True, False,  True, False,  True, False])

In [14]:
array1[mask]

array([2, 4, 6, 8])

In [15]:
array1.cumsum()

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45], dtype=int32)

In [16]:
array1.cumprod()

array([     1,      2,      6,     24,    120,    720,   5040,  40320,
       362880], dtype=int32)

In [18]:
arr2 = np.arange(0, 50, 5)

arr2

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [19]:
arr2.dtype

dtype('int32')

In [20]:
arr3 = np.eye(3)

arr3

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [21]:
arr4 = np.diag(np.arange(1, 5, 1))
arr4

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [23]:
print(np.linspace(0, 10, 15))

[ 0.          0.71428571  1.42857143  2.14285714  2.85714286  3.57142857
  4.28571429  5.          5.71428571  6.42857143  7.14285714  7.85714286
  8.57142857  9.28571429 10.        ]


In [25]:
print(np.logspace(0, 5, 10))

[1.00000000e+00 3.59381366e+00 1.29154967e+01 4.64158883e+01
 1.66810054e+02 5.99484250e+02 2.15443469e+03 7.74263683e+03
 2.78255940e+04 1.00000000e+05]


In [39]:
array5 = np.array([[1, 2, 3, 4, 5, 6, 7, 8, 9], [9, 8, 7, 6, 5, 4, 3, 2, 1]])

array5

array([[1, 2, 3, 4, 5, 6, 7, 8, 9],
       [9, 8, 7, 6, 5, 4, 3, 2, 1]])

In [46]:
arr6 = np.matrix([[1, 2, 3, 4, 5, 6, 7, 8, 9], [1, 1, 1, 1, 1, 1, 1, 1, 1], [9, 8, 7, 6, 5, 4, 3, 2, 1]])
# arr6.size
# np.shape(arr6)
arr6


matrix([[1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 1, 1, 1, 1, 1, 1, 1, 1],
        [9, 8, 7, 6, 5, 4, 3, 2, 1]])

In [47]:
arr6.dtype

dtype('int32')

In [50]:
arr6[0:3, 2:5]

matrix([[3, 4, 5],
        [1, 1, 1],
        [7, 6, 5]])

In [52]:
arr_with_type = np.array([2, 3, 4], dtype=float)

arr_with_type.dtype

dtype('float64')

In [53]:
arr6.itemsize

4

In [54]:
arr6.nbytes

108

In [55]:
arr6.ndim

2

In [64]:
arr7 = np.array([
    [
        [6, 7, 8, 9],
        [1, 1, 1, 1],
        [4, 30, 2, 1]
    ],
    [
        [1, 2, 3, 4],
        [1, 1, 1, 1],
        [9, 8, 7, 6]
    ]
])

arr7

array([[[ 6,  7,  8,  9],
        [ 1,  1,  1,  1],
        [ 4, 30,  2,  1]],

       [[ 1,  2,  3,  4],
        [ 1,  1,  1,  1],
        [ 9,  8,  7,  6]]])

In [61]:
arr7.ndim

3

In [62]:
arr7.shape

(2, 3, 4)

In [65]:
arr7[0, 2, 1]

30

In [67]:
arr8 = np.array([
    [
        [
            [1, 2, 3, 4, 5],
            [6, 7, 8, 9, 10],
            [11, 12, 13, 14, 15],
            [16, 17, 18, 19, 20]
        ],
        [
            [21, 22, 23, 24, 25],
            [26, 27, 28, 29, 30],
            [31, 32, 33, 34, 35],
            [36, 37, 38, 39, 40]
        ],
        [
            [41, 42, 43, 44, 45],
            [46, 47, 48, 49, 50],
            [51, 52, 53, 54, 55],
            [56, 57, 58, 59, 60]
        ]
    ],
    [
        [
            [61, 62, 63, 64, 65],
            [66, 67, 68, 69, 70],
            [71, 72, 73, 74, 75],
            [76, 77, 78, 79, 80]
        ],
        [
            [81, 82, 83, 84, 85],
            [86, 87, 88, 89, 90],
            [91, 92, 93, 94, 95],
            [96, 97, 98, 99, 100]
        ],
        [
            [101, 102, 103, 104, 105],
            [106, 107, 108, 109, 110],
            [111, 112, 113, 114, 115],
            [116, 117, 118, 119, 120]
        ]
    ]
])

arr8

array([[[[  1,   2,   3,   4,   5],
         [  6,   7,   8,   9,  10],
         [ 11,  12,  13,  14,  15],
         [ 16,  17,  18,  19,  20]],

        [[ 21,  22,  23,  24,  25],
         [ 26,  27,  28,  29,  30],
         [ 31,  32,  33,  34,  35],
         [ 36,  37,  38,  39,  40]],

        [[ 41,  42,  43,  44,  45],
         [ 46,  47,  48,  49,  50],
         [ 51,  52,  53,  54,  55],
         [ 56,  57,  58,  59,  60]]],


       [[[ 61,  62,  63,  64,  65],
         [ 66,  67,  68,  69,  70],
         [ 71,  72,  73,  74,  75],
         [ 76,  77,  78,  79,  80]],

        [[ 81,  82,  83,  84,  85],
         [ 86,  87,  88,  89,  90],
         [ 91,  92,  93,  94,  95],
         [ 96,  97,  98,  99, 100]],

        [[101, 102, 103, 104, 105],
         [106, 107, 108, 109, 110],
         [111, 112, 113, 114, 115],
         [116, 117, 118, 119, 120]]]])

In [68]:
arr8.ndim

4

In [69]:
arr8.shape

(2, 3, 4, 5)

In [72]:
arr8[1, 1, 2, 4]

95