In [72]:
import pandas as pd
import numpy as np
import random

In [73]:
data = pd.read_csv("data/census.csv")

data.shape

(32561, 15)

In [74]:
data.head()

age          workclass  final-weight   education  education-num  \
0   39          State-gov         77516   Bachelors             13   
1   50   Self-emp-not-inc         83311   Bachelors             13   
2   38            Private        215646     HS-grad              9   
3   53            Private        234721        11th              7   
4   28            Private        338409   Bachelors             13   

        marital-status          occupation    relationship    race      sex  \
0        Never-married        Adm-clerical   Not-in-family   White     Male   
1   Married-civ-spouse     Exec-managerial         Husband   White     Male   
2             Divorced   Handlers-cleaners   Not-in-family   White     Male   
3   Married-civ-spouse   Handlers-cleaners         Husband   Black     Male   
4   Married-civ-spouse      Prof-specialty            Wife   Black   Female   

   capital-gain  capital-loos  hour-per-week  native-country  income  
0          2174             0             40   United-States   <=50K  
1             0             0             13   United-States   <=50K  
2             0             0             40   United-States   <=50K  
3             0             0             40   United-States   <=50K  
4             0             0             40            Cuba   <=50K

In [75]:
data.tail()

age      workclass  final-weight    education  education-num  \
32556   27        Private        257302   Assoc-acdm             12   
32557   40        Private        154374      HS-grad              9   
32558   58        Private        151910      HS-grad              9   
32559   22        Private        201490      HS-grad              9   
32560   52   Self-emp-inc        287927      HS-grad              9   

            marital-status          occupation relationship    race      sex  \
32556   Married-civ-spouse        Tech-support         Wife   White   Female   
32557   Married-civ-spouse   Machine-op-inspct      Husband   White     Male   
32558              Widowed        Adm-clerical    Unmarried   White   Female   
32559        Never-married        Adm-clerical    Own-child   White     Male   
32560   Married-civ-spouse     Exec-managerial         Wife   White   Female   

       capital-gain  capital-loos  hour-per-week  native-country  income  
32556             0             0             38   United-States   <=50K  
32557             0             0             40   United-States    >50K  
32558             0             0             40   United-States   <=50K  
32559             0             0             20   United-States   <=50K  
32560         15024             0             40   United-States    >50K

# Simple Random Sampling

In [76]:
df_sample = data.sample(n=1000, replace=False)

df_sample.shape

(1000, 15)

In [77]:
def get_random_sample(data, n):
    return data.sample(n=n, replace=False)

df_sample = get_random_sample(data, 1000)

df_sample.shape

(1000, 15)

# Systematic Sampling

In [78]:
data.shape

(32561, 15)

In [79]:
random.randint(0, len(data) // 100)

81

In [80]:
np.arange(random.randint(0, len(data) // 100), len(data), len(data) // 100)

array([   46,   371,   696,  1021,  1346,  1671,  1996,  2321,  2646,
        2971,  3296,  3621,  3946,  4271,  4596,  4921,  5246,  5571,
        5896,  6221,  6546,  6871,  7196,  7521,  7846,  8171,  8496,
        8821,  9146,  9471,  9796, 10121, 10446, 10771, 11096, 11421,
       11746, 12071, 12396, 12721, 13046, 13371, 13696, 14021, 14346,
       14671, 14996, 15321, 15646, 15971, 16296, 16621, 16946, 17271,
       17596, 17921, 18246, 18571, 18896, 19221, 19546, 19871, 20196,
       20521, 20846, 21171, 21496, 21821, 22146, 22471, 22796, 23121,
       23446, 23771, 24096, 24421, 24746, 25071, 25396, 25721, 26046,
       26371, 26696, 27021, 27346, 27671, 27996, 28321, 28646, 28971,
       29296, 29621, 29946, 30271, 30596, 30921, 31246, 31571, 31896,
       32221, 32546])

In [81]:
def systematic_sample(data, n=100):
    indices = np.arange(random.randint(0, len(data) // n), len(data), len(data) // 100)
    return data.iloc[indices]


df_sample = systematic_sample(data)

df_sample

age workclass  final-weight      education  education-num  \
42      24   Private        172987      Bachelors             13   
367     22   Private        362589     Assoc-acdm             12   
692     42   Private        262425   Some-college             10   
1017    51   Private        191965        HS-grad              9   
1342    47   Private         46857   Some-college             10   
...    ...       ...           ...            ...            ...   
31242   36   Private        132879        1st-4th              2   
31567   30   Private        147430        HS-grad              9   
31892   55   Private         92215        HS-grad              9   
32217   22   Private        193090        HS-grad              9   
32542   72         ?        129912        HS-grad              9   

               marital-status          occupation    relationship    race  \
42         Married-civ-spouse        Tech-support         Husband   White   
367             Never-married               Sales   Not-in-family   White   
692        Married-civ-spouse      Prof-specialty         Husband   White   
1017                  Widowed       Other-service       Unmarried   White   
1342                 Divorced        Adm-clerical   Not-in-family   White   
...                       ...                 ...             ...     ...   
31242      Married-civ-spouse   Handlers-cleaners         Husband   White   
31567   Married-spouse-absent        Adm-clerical   Not-in-family   White   
31892           Never-married        Adm-clerical   Not-in-family   White   
32217           Never-married               Sales   Not-in-family   White   
32542      Married-civ-spouse                   ?         Husband   White   

           sex  capital-gain  capital-loos  hour-per-week  native-country  \
42        Male             0             0             50   United-States   
367     Female             0             0             15   United-States   
692       Male             0             0             50   United-States   
1017    Female             0             0             32   United-States   
1342      Male             0             0             40   United-States   
...        ...           ...           ...            ...             ...   
31242     Male             0             0             40           Italy   
31567   Female             0             0             40   United-States   
31892   Female             0             0             45   United-States   
32217   Female             0             0             37   United-States   
32542     Male             0             0             25   United-States   

       income  
42      <=50K  
367     <=50K  
692     <=50K  
1017    <=50K  
1342    <=50K  
...       ...  
31242   <=50K  
31567   <=50K  
31892   <=50K  
32217   <=50K  
32542   <=50K  

[101 rows x 15 columns]

# Cluster Sampling

In [82]:
groupSize = len(data) // 10

groups = []
groupId = 0
counter = 0

for _ in range(len(data)):
    groups.append(groupId)
    counter += 1
    if counter > groupSize:
        counter = 0
        groupId += 1


np.unique(groups, return_counts=True)

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([3257, 3257, 3257, 3257, 3257, 3257, 3257, 3257, 3257, 3248]))

In [83]:
np.shape(groups), data.shape

((32561,), (32561, 15))

In [84]:
data['group'] = groups

data.head(10)

age          workclass  final-weight   education  education-num  \
0   39          State-gov         77516   Bachelors             13   
1   50   Self-emp-not-inc         83311   Bachelors             13   
2   38            Private        215646     HS-grad              9   
3   53            Private        234721        11th              7   
4   28            Private        338409   Bachelors             13   
5   37            Private        284582     Masters             14   
6   49            Private        160187         9th              5   
7   52   Self-emp-not-inc        209642     HS-grad              9   
8   31            Private         45781     Masters             14   
9   42            Private        159449   Bachelors             13   

           marital-status          occupation    relationship    race  \
0           Never-married        Adm-clerical   Not-in-family   White   
1      Married-civ-spouse     Exec-managerial         Husband   White   
2                Divorced   Handlers-cleaners   Not-in-family   White   
3      Married-civ-spouse   Handlers-cleaners         Husband   Black   
4      Married-civ-spouse      Prof-specialty            Wife   Black   
5      Married-civ-spouse     Exec-managerial            Wife   White   
6   Married-spouse-absent       Other-service   Not-in-family   Black   
7      Married-civ-spouse     Exec-managerial         Husband   White   
8           Never-married      Prof-specialty   Not-in-family   White   
9      Married-civ-spouse     Exec-managerial         Husband   White   

       sex  capital-gain  capital-loos  hour-per-week  native-country  income  \
0     Male          2174             0             40   United-States   <=50K   
1     Male             0             0             13   United-States   <=50K   
2     Male             0             0             40   United-States   <=50K   
3     Male             0             0             40   United-States   <=50K   
4   Female             0             0             40            Cuba   <=50K   
5   Female             0             0             40   United-States   <=50K   
6   Female             0             0             16         Jamaica   <=50K   
7     Male             0             0             45   United-States    >50K   
8   Female         14084             0             50   United-States    >50K   
9     Male          5178             0             40   United-States    >50K   

   group  
0      0  
1      0  
2      0  
3      0  
4      0  
5      0  
6      0  
7      0  
8      0  
9      0

In [85]:
data_grouped = data[data['group'] == random.randint(0, 9)]

data_grouped.shape

(3257, 16)

In [86]:
data_grouped['group'].value_counts()

group
0    3257
Name: count, dtype: int64

In [87]:
def group_sampling(data, group_count):
    groupSize = len(data) // group_count
    groups = []
    groupId = 0
    counter = 0

    for _ in range(len(data)):
        groups.append(groupId)
        counter += 1
        if counter > groupSize:
            counter = 0
            groupId += 1

    data['group'] = groups
    data_grouped = data[data['group'] == random.randint(0, group_count-1)]
    return data_grouped

df_group_sample = group_sampling(data, 100)

df_group_sample.shape, df_group_sample['group'].value_counts()

((326, 16),
 group
 19    326
 Name: count, dtype: int64)

In [88]:
df_group_sample.head()

age workclass  final-weight      education  education-num  \
6194   17   Private        198146           11th              7   
6195   21   Private        337766   Some-college             10   
6196   42   Private        210525   Some-college             10   
6197   42   Private        185602        HS-grad              9   
6198   36   Private        173804           11th              7   

           marital-status        occupation    relationship    race      sex  \
6194        Never-married             Sales       Own-child   White   Female   
6195   Married-civ-spouse      Adm-clerical         Husband   White     Male   
6196   Married-civ-spouse      Tech-support         Husband   White     Male   
6197   Married-civ-spouse   Exec-managerial            Wife   White   Female   
6198             Divorced     Other-service   Not-in-family   White   Female   

      capital-gain  capital-loos  hour-per-week  native-country  income  group  
6194             0             0             15   United-States   <=50K     19  
6195             0             0             40   United-States   <=50K     19  
6196             0             0             20   United-States    >50K     19  
6197             0             0             40   United-States    >50K     19  
6198             0             0             40   United-States   <=50K     19